# Site settings
title: Rovansteen 
email: rovansteen@me.com 
description: > 
    'Hi, my name is Robert van Steen. I build websites.'
baseurl: ''
url: 'beta.rovansteen.com' # the base hostname & protocol for your site
twitter_username: rovansteen
github_username:  rovansteen

# Build settings
markdown: kramdown
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock']
